# Generated by Django 5.1.1 on 2025-06-21 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Device_register',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dispositivo de registro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='create_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ip_register',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de registro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_account_creator',
            field=models.BooleanField(default=False, help_text='Puede crear cuentas de usuario', verbose_name='creador de cuentas'),
        ),
    ]
