# Generated by Django 5.1.1 on 2025-06-21 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0002_customuser_device_register_customuser_create_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido (ej: 12345678-9)', regex='^0*(\\d{1,3}(\\.?\\d{3})*\\-?[\\dkK])$')], verbose_name='RUT'),
        ),
    ]
