"""
Django settings for gestionvaldivia project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

LOGOUT_REDIRECT_URL = 'login'  # Redirige a la página de inicio de sesión después del cierre de sesión

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m+bsa(jfl2#p3!c9ai@$uiwlcaqnm7+c&@&jak@%0d_uzv4y=f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/admin_panel/'  # Redirige al panel de administración después del inicio de sesión
LOGOUT_REDIRECT_URL = 'index'  # Redirige a la página de inicio después del cierre de sesión

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'appgestion.CustomUser'  # Usar el modelo de usuario personalizado
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appgestion.apps.AppgestionConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestionvaldivia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestionvaldivia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gestionsslr',
        'USER': 'root',
        'PASSWORD': 'Chepita',
        'HOST': 'localhost',
        'PORT': '3306',
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Cambiado a 8 caracteres
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 # Configuración de sesión segura (requerido para normativa chilena)

SESSION_COOKIE_SECURE = True  # Las cookies de sesión solo se envían a través de HTTPS
CSRF_COOKIE_SECURE = True  # Las cookies CSRF solo se envían a través de HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # La sesión expira al cerrar el navegador
SESSION_COOKIE_AGE = 1800 # 30 minutos de inactividad antes de que la sesión expire
SESSION_SAVE_EVERY_REQUEST = True  # Guarda la sesión en cada solicitud para actualizar el tiempo de expiración


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Archivos estáticos (CSS, JavaScript, Images)
STATIC_URL = '/static/'
 # Donde buscan los archivos estáticos
STATIC_ROOT = os.path.join(BASE_DIR, 'static')    # Donde se recolectan para producción
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'appgestion/static')] 
# Archivos multimedia (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')    
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
# Power BI y Excel Manager
POWER_BI_EMBED_URL = os.getenv('POWER_BI_EMBED_URL', 'https://app.powerbi.com')
POWER_BI_CLIENT_ID = os.getenv('POWER_BI_CLIENT_ID', 'your-client-id')
POWER_BI_TENANT_ID = os.getenv('POWER_BI_TENANT_ID', 'your-tenant-id')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
